### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot.io#6]
I get a certificate error connecting to this site in firefox

**Comment by pfrazee** [comment]
Huh, yeah I get that in FF as well, but not Chrome. I used lets encrypt.

**Comment by dominictarr** [comment]
that is weird! isn't mozilla behind lets encrypt?

**Comment by pfrazee** [comment]
https://community.letsencrypt.org/t/cert-not-work-in-firefox/5272/11 may
help

**Comment by pfrazee** [comment]
yeah it looks like I have a few misconfigurations. This, in particular, is
because I didnt include my intermediary cert chain

**Comment by pfrazee** [comment]
Fixed
