### ISSUE TITLE
Post Message page's See Also links 404

### ISSUE THREAD

**Issue by kwijibo** [ssbc/scuttlebot.io#9]
On this page: https://scuttlebot.io/docs/message-types/post.html some of the See Also links (defined here: https://github.com/ssbc/scuttlebot.io/blob/master/tmpl/docs/message-types/post.html.js ) 404
The dead links are:
- https://scuttlebot.io/docs/advanced/message-schemas.html
- https://scuttlebot.io/docs/advanced/linking-messages.html

I'm not sure if the links are wrong or the pages don't exist. If they do exist, these might be the right matches:
- https://github.com/ssbc/scuttlebot.io/blob/master/tmpl/docs/message-types/custom-types.md
- https://github.com/ssbc/scuttlebot.io/blob/master/tmpl/docs/advanced/links.md

**Comment by clehner** [comment]
Thanks for reporting. I think those are probably what the links should go to. I will update them.
